apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod
  namespace: jaeger
  labels:
    app: hotrod
spec:
  selector:
    matchLabels:
      app: hotrod
  replicas: 1
  template:
    metadata:
      labels:
        app: hotrod
    spec:
      containers:
        - name: promtail-agent
          image: jaegertracing/example-hotrod:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAEGER_AGENT_HOST
              value: jaeger-agent
      securityContext:
        runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod
  namespace: jaeger
  labels:
    app: hotrod
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: hotrod