apiVersion: apps/v1
kind: Deployment
metadata:
  name: clymene-ingester
  namespace: clymene
  labels:
    app: clymene-ingester
spec:
  selector:
    matchLabels:
      app: clymene-ingester
  replicas: 3
  template:
    metadata:
      labels:
        app: clymene-ingester
    spec:
      containers:
        - name: ingester
          image: bourbonkk/clymene-ingester:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 15694
          args:
            - --prometheus.remote.url=http://prometheus-server-http.prometheus:9090/api/v1/write
            - --es.server-urls=http://elasticsearch.es:9200
            - --log-level=info
#            - --kafka.consumer.brokers=kafka.kafka:9092
#            - --influxdb.url=http://influxdb.influxdb:8086
#            - --influxdb.token=6nfP-k1yvSd6nxXWBna_1cW9Dgt-37Z3RfjhSMjWyuZEGYSMxd_5nHDxbg8pVjFEsoO2G2hpqr311XKVklqC9A==
#            - --influxdb.org=clymene
#            - --influxdb.bucket=clymene
#            - --opentsdb.host=opentsdb.opentsdb
          env:
            - name: STORAGE_TYPE
              value: prometheus,elasticsearch # opentsdb # prometheus,elasticsearch,influxdb,opentsdb
      securityContext:
        runAsUser: 1000