# rbac.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: clymene
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clymene
  namespace: clymene
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: clymene
---
apiVersion: rbac.authorization.k8s.io/v1  # kubernetes 1.22+
kind: ClusterRole
metadata:
  name: clymene
  namespace: clymene
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1 # kubernetes 1.22+
kind: ClusterRoleBinding
metadata:
  name: clymene
subjects:
  - kind: ServiceAccount
    name: clymene
    namespace: clymene
roleRef:
  kind: ClusterRole
  name: clymene
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1 # kubernetes 1.22+
kind: ClusterRoleBinding
metadata:
  name: clymene-default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: clymene
roleRef:
  kind: ClusterRole
  name: clymene
  apiGroup: rbac.authorization.k8s.io
---