{
 "title": "k8s monitoring using druid",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "container cpu time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "select cpu1.\"cluster\",\n    cpu1.\"job\",\n    cpu1.\"instance\",\n    cpu1.\"namespace\",\n    cpu1.\"pod\",\n    cpu1.\"cpu_time\" - cpu2.\"cpu_time\" as cpuTime,\n    cpu1.__timestamp\nfrom (select TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n             \"__name__\"                                       AS \"__name__\",\n             \"cluster\"                                        AS \"cluster\",\n             \"job\"                                            AS \"job\",\n             \"instance\"                                       AS \"instance\",\n             \"namespace\"                                      AS \"namespace\",\n             \"pod\"                                            AS \"pod\",\n             sum(\"value\")                                     AS \"cpu_time\"\n      from \"druid\".\"clymene\"\n      WHERE \"__name__\" = 'container_cpu_usage_seconds_total'\n        AND \"pod\" !=''\n      GROUP BY \"__name__\",\n          \"cluster\",\n          \"job\",\n          \"instance\",\n          \"namespace\",\n          \"pod\",\n          TIME_FLOOR(CAST (\"__time\" AS TIMESTAMP), 'PT30S')) cpu1\n         left join (select TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                           \"__name__\"                                       AS \"__name__\",\n                           \"cluster\"                                        AS \"cluster\",\n                           \"job\"                                            AS \"job\",\n                           \"instance\"                                       AS \"instance\",\n                           \"namespace\"                                      AS \"namespace\",\n                           \"pod\"                                            AS \"pod\",\n                           sum(\"value\")                                     AS \"cpu_time\"\n                    from \"druid\".\"clymene\"\n                    WHERE \"__name__\" = 'container_cpu_usage_seconds_total'\n                      AND \"pod\" !=''\n                    GROUP BY \"__name__\",\n                        \"cluster\",\n                        \"job\",\n                        \"instance\",\n                        \"namespace\",\n                        \"pod\",\n                        TIME_FLOOR(CAST (\"__time\" AS TIMESTAMP), 'PT30S')) cpu2\n                   on cpu1.\"__timestamp\" = cpu2.\"__timestamp\" + INTERVAL '30' SECOND\n    AND cpu1.\"namespace\"=cpu2.\"namespace\"\n    AND cpu1.\"pod\"=cpu2.\"pod\"\nwhere cpu1.\"__timestamp\" >= MILLIS_TO_TIMESTAMP(${__from})\n    AND cpu1.\"__timestamp\" < MILLIS_TO_TIMESTAMP(${__to})",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"select cpu1.\\\"cluster\\\",\\n    cpu1.\\\"job\\\",\\n    cpu1.\\\"instance\\\",\\n    cpu1.\\\"namespace\\\",\\n    cpu1.\\\"pod\\\",\\n    cpu1.\\\"cpu_time\\\" - cpu2.\\\"cpu_time\\\" as cpuTime,\\n    cpu1.__timestamp\\nfrom (select TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n             \\\"__name__\\\"                                       AS \\\"__name__\\\",\\n             \\\"cluster\\\"                                        AS \\\"cluster\\\",\\n             \\\"job\\\"                                            AS \\\"job\\\",\\n             \\\"instance\\\"                                       AS \\\"instance\\\",\\n             \\\"namespace\\\"                                      AS \\\"namespace\\\",\\n             \\\"pod\\\"                                            AS \\\"pod\\\",\\n             sum(\\\"value\\\")                                     AS \\\"cpu_time\\\"\\n      from \\\"druid\\\".\\\"clymene\\\"\\n      WHERE \\\"__name__\\\" = 'container_cpu_usage_seconds_total'\\n        AND \\\"pod\\\" !=''\\n      GROUP BY \\\"__name__\\\",\\n          \\\"cluster\\\",\\n          \\\"job\\\",\\n          \\\"instance\\\",\\n          \\\"namespace\\\",\\n          \\\"pod\\\",\\n          TIME_FLOOR(CAST (\\\"__time\\\" AS TIMESTAMP), 'PT30S')) cpu1\\n         left join (select TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                           \\\"__name__\\\"                                       AS \\\"__name__\\\",\\n                           \\\"cluster\\\"                                        AS \\\"cluster\\\",\\n                           \\\"job\\\"                                            AS \\\"job\\\",\\n                           \\\"instance\\\"                                       AS \\\"instance\\\",\\n                           \\\"namespace\\\"                                      AS \\\"namespace\\\",\\n                           \\\"pod\\\"                                            AS \\\"pod\\\",\\n                           sum(\\\"value\\\")                                     AS \\\"cpu_time\\\"\\n                    from \\\"druid\\\".\\\"clymene\\\"\\n                    WHERE \\\"__name__\\\" = 'container_cpu_usage_seconds_total'\\n                      AND \\\"pod\\\" !=''\\n                    GROUP BY \\\"__name__\\\",\\n                        \\\"cluster\\\",\\n                        \\\"job\\\",\\n                        \\\"instance\\\",\\n                        \\\"namespace\\\",\\n                        \\\"pod\\\",\\n                        TIME_FLOOR(CAST (\\\"__time\\\" AS TIMESTAMP), 'PT30S')) cpu2\\n                   on cpu1.\\\"__timestamp\\\" = cpu2.\\\"__timestamp\\\" + INTERVAL '30' SECOND\\n    AND cpu1.\\\"namespace\\\"=cpu2.\\\"namespace\\\"\\n    AND cpu1.\\\"pod\\\"=cpu2.\\\"pod\\\"\\nwhere cpu1.\\\"__timestamp\\\" >= MILLIS_TO_TIMESTAMP(${__from})\\n    AND cpu1.\\\"__timestamp\\\" < MILLIS_TO_TIMESTAMP(${__to})\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "select cpu1.\"cpu_time\" - cpu2.\"cpu_time\" AS cpu_time,\ncpu1.__timestamp\nfrom (select TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n             \"__name__\"                                       AS \"__name__\",\n             \"cluster\"                                        AS \"cluster\",\n             \"job\"                                            AS \"job\",\n             \"instance\"                                       AS \"instance\",\n             sum(\"value\")                                     AS \"cpu_time\"\n      from \"druid\".\"clymene\"\n      WHERE \"__name__\" = 'node_cpu_seconds_total'\n        AND \"mode\" != 'idle'\n      GROUP BY \"__name__\",\n          \"cluster\",\n          \"job\",\n          \"instance\",\n          TIME_FLOOR(CAST (\"__time\" AS TIMESTAMP), 'PT30S')) cpu1\n         left join (select TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                           \"__name__\"                                       AS \"__name__\",\n                           \"cluster\"                                        AS \"cluster\",\n                           \"job\"                                            AS \"job\",\n                           \"instance\"                                       AS \"instance\",\n                           sum(\"value\")                                     AS \"cpu_time\"\n                    from \"druid\".\"clymene\"\n                    WHERE \"__name__\" = 'node_cpu_seconds_total'\n                      AND \"mode\" != 'idle'\n                    GROUP BY \"__name__\",\n                        \"cluster\",\n                        \"job\",\n                        \"instance\",\n                        TIME_FLOOR(CAST (\"__time\" AS TIMESTAMP), 'PT30S')) cpu2\n        on cpu1.__timestamp = cpu2.__timestamp + INTERVAL '30' SECOND\nwhere cpu1.\"__timestamp\" >= MILLIS_TO_TIMESTAMP(${__from})\n  AND cpu1.\"__timestamp\" < MILLIS_TO_TIMESTAMP(${__to})",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"select cpu1.\\\"cpu_time\\\" - cpu2.\\\"cpu_time\\\" AS cpu_time,\\ncpu1.__timestamp\\nfrom (select TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n             \\\"__name__\\\"                                       AS \\\"__name__\\\",\\n             \\\"cluster\\\"                                        AS \\\"cluster\\\",\\n             \\\"job\\\"                                            AS \\\"job\\\",\\n             \\\"instance\\\"                                       AS \\\"instance\\\",\\n             sum(\\\"value\\\")                                     AS \\\"cpu_time\\\"\\n      from \\\"druid\\\".\\\"clymene\\\"\\n      WHERE \\\"__name__\\\" = 'node_cpu_seconds_total'\\n        AND \\\"mode\\\" != 'idle'\\n      GROUP BY \\\"__name__\\\",\\n          \\\"cluster\\\",\\n          \\\"job\\\",\\n          \\\"instance\\\",\\n          TIME_FLOOR(CAST (\\\"__time\\\" AS TIMESTAMP), 'PT30S')) cpu1\\n         left join (select TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                           \\\"__name__\\\"                                       AS \\\"__name__\\\",\\n                           \\\"cluster\\\"                                        AS \\\"cluster\\\",\\n                           \\\"job\\\"                                            AS \\\"job\\\",\\n                           \\\"instance\\\"                                       AS \\\"instance\\\",\\n                           sum(\\\"value\\\")                                     AS \\\"cpu_time\\\"\\n                    from \\\"druid\\\".\\\"clymene\\\"\\n                    WHERE \\\"__name__\\\" = 'node_cpu_seconds_total'\\n                      AND \\\"mode\\\" != 'idle'\\n                    GROUP BY \\\"__name__\\\",\\n                        \\\"cluster\\\",\\n                        \\\"job\\\",\\n                        \\\"instance\\\",\\n                        TIME_FLOOR(CAST (\\\"__time\\\" AS TIMESTAMP), 'PT30S')) cpu2\\n        on cpu1.__timestamp = cpu2.__timestamp + INTERVAL '30' SECOND\\nwhere cpu1.\\\"__timestamp\\\" >= MILLIS_TO_TIMESTAMP(${__from})\\n  AND cpu1.\\\"__timestamp\\\" < MILLIS_TO_TIMESTAMP(${__to})\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 } },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "select\n    total.__timestamp,\n    total.__name__,\n    total.cluster,\n    total.job,\n    total.instance,\n    (total.mem_total - mem_free.memFree - (mem_cached.memCached + mem_buffer.memBuffer + mem_sr.memSr))/1024/1024/1024 as memoryUsed\nfrom (select TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n             \"__name__\"                                       AS \"__name__\",\n             \"cluster\"                                        AS \"cluster\",\n             \"job\"                                            AS \"job\",\n             \"instance\"                                       AS \"instance\",\n             \"mode\"                                           AS \"mode\",\n             avg(\"value\")                                     AS \"mem_total\"\n      from \"druid\".\"clymene\"\n      WHERE \"__name__\" = 'node_memory_MemTotal_bytes'\n      GROUP BY \"__name__\",\n               \"cluster\",\n               \"job\",\n               \"instance\",\n               \"mode\",\n               TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) total\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memFree\"\n                    FROM \"druid\".\"clymene\"\n                    WHERE \"__name__\" = 'node_memory_MemFree_bytes'\n                    GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_free\n             on total.__timestamp = mem_free.__timestamp\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memCached\"\n                   FROM \"druid\".\"clymene\"\n                   WHERE \"__name__\" = 'node_memory_Cached_bytes'\n                   GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_cached\n             on total.__timestamp = mem_cached.__timestamp\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memBuffer\"\n                   FROM \"druid\".\"clymene\"\n                   WHERE \"__name__\" = 'node_memory_Buffers_bytes'\n                   GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_buffer\n             on total.__timestamp = mem_buffer.__timestamp\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memSr\"\n                   FROM \"druid\".\"clymene\"\n                   WHERE \"__name__\" = 'node_memory_SReclaimable_bytes'\n                   GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_sr\n             on total.__timestamp = mem_sr.__timestamp\nwhere total.__timestamp >= MILLIS_TO_TIMESTAMP(${__from})\n  AND total.__timestamp < MILLIS_TO_TIMESTAMP(${__to})",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"select\\n    total.__timestamp,\\n    total.__name__,\\n    total.cluster,\\n    total.job,\\n    total.instance,\\n    (total.mem_total - mem_free.memFree - (mem_cached.memCached + mem_buffer.memBuffer + mem_sr.memSr))/1024/1024/1024 as memoryUsed\\nfrom (select TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n             \\\"__name__\\\"                                       AS \\\"__name__\\\",\\n             \\\"cluster\\\"                                        AS \\\"cluster\\\",\\n             \\\"job\\\"                                            AS \\\"job\\\",\\n             \\\"instance\\\"                                       AS \\\"instance\\\",\\n             \\\"mode\\\"                                           AS \\\"mode\\\",\\n             avg(\\\"value\\\")                                     AS \\\"mem_total\\\"\\n      from \\\"druid\\\".\\\"clymene\\\"\\n      WHERE \\\"__name__\\\" = 'node_memory_MemTotal_bytes'\\n      GROUP BY \\\"__name__\\\",\\n               \\\"cluster\\\",\\n               \\\"job\\\",\\n               \\\"instance\\\",\\n               \\\"mode\\\",\\n               TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) total\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memFree\\\"\\n                    FROM \\\"druid\\\".\\\"clymene\\\"\\n                    WHERE \\\"__name__\\\" = 'node_memory_MemFree_bytes'\\n                    GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_free\\n             on total.__timestamp = mem_free.__timestamp\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memCached\\\"\\n                   FROM \\\"druid\\\".\\\"clymene\\\"\\n                   WHERE \\\"__name__\\\" = 'node_memory_Cached_bytes'\\n                   GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_cached\\n             on total.__timestamp = mem_cached.__timestamp\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memBuffer\\\"\\n                   FROM \\\"druid\\\".\\\"clymene\\\"\\n                   WHERE \\\"__name__\\\" = 'node_memory_Buffers_bytes'\\n                   GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_buffer\\n             on total.__timestamp = mem_buffer.__timestamp\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memSr\\\"\\n                   FROM \\\"druid\\\".\\\"clymene\\\"\\n                   WHERE \\\"__name__\\\" = 'node_memory_SReclaimable_bytes'\\n                   GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_sr\\n             on total.__timestamp = mem_sr.__timestamp\\nwhere total.__timestamp >= MILLIS_TO_TIMESTAMP(${__from})\\n  AND total.__timestamp < MILLIS_TO_TIMESTAMP(${__to})\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "builder": {
      "intervals": {
       "intervals": [
        "${__from:date:iso}/${__to:date:iso}"
       ],
       "type": "intervals"
      },
      "query": "select\n    total.__timestamp,\n    total.__name__,\n    total.cluster,\n    total.job,\n    total.instance,\n    ROUND((total.mem_total - mem_free.memFree - (mem_cached.memCached + mem_buffer.memBuffer + mem_sr.memSr)) / total.mem_total * 100, 2) as memUtilization\nfrom (select TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n             \"__name__\"                                       AS \"__name__\",\n             \"cluster\"                                        AS \"cluster\",\n             \"job\"                                            AS \"job\",\n             \"instance\"                                       AS \"instance\",\n             \"mode\"                                           AS \"mode\",\n             avg(\"value\")                                     AS \"mem_total\"\n      from \"druid\".\"clymene\"\n      WHERE \"__name__\" = 'node_memory_MemTotal_bytes'\n      GROUP BY \"__name__\",\n               \"cluster\",\n               \"job\",\n               \"instance\",\n               \"mode\",\n               TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) total\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memFree\"\n                    FROM \"druid\".\"clymene\"\n                    WHERE \"__name__\" = 'node_memory_MemFree_bytes'\n                    GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_free\n             on total.__timestamp = mem_free.__timestamp\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memCached\"\n                   FROM \"druid\".\"clymene\"\n                   WHERE \"__name__\" = 'node_memory_Cached_bytes'\n                   GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_cached\n             on total.__timestamp = mem_cached.__timestamp\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memBuffer\"\n                   FROM \"druid\".\"clymene\"\n                   WHERE \"__name__\" = 'node_memory_Buffers_bytes'\n                   GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_buffer\n             on total.__timestamp = mem_buffer.__timestamp\n        left join (SELECT TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S') AS \"__timestamp\",\n                          avg(\"value\")                                     AS \"memSr\"\n                   FROM \"druid\".\"clymene\"\n                   WHERE \"__name__\" = 'node_memory_SReclaimable_bytes'\n                   GROUP BY TIME_FLOOR(CAST(\"__time\" AS TIMESTAMP), 'PT30S')) mem_sr\n             on total.__timestamp = mem_sr.__timestamp\nwhere total.__timestamp >= MILLIS_TO_TIMESTAMP(${__from})\n  AND total.__timestamp < MILLIS_TO_TIMESTAMP(${__to})",
      "queryType": "sql"
     },
     "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"select\\n    total.__timestamp,\\n    total.__name__,\\n    total.cluster,\\n    total.job,\\n    total.instance,\\n    ROUND((total.mem_total - mem_free.memFree - (mem_cached.memCached + mem_buffer.memBuffer + mem_sr.memSr)) / total.mem_total * 100, 2) as memUtilization\\nfrom (select TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n             \\\"__name__\\\"                                       AS \\\"__name__\\\",\\n             \\\"cluster\\\"                                        AS \\\"cluster\\\",\\n             \\\"job\\\"                                            AS \\\"job\\\",\\n             \\\"instance\\\"                                       AS \\\"instance\\\",\\n             \\\"mode\\\"                                           AS \\\"mode\\\",\\n             avg(\\\"value\\\")                                     AS \\\"mem_total\\\"\\n      from \\\"druid\\\".\\\"clymene\\\"\\n      WHERE \\\"__name__\\\" = 'node_memory_MemTotal_bytes'\\n      GROUP BY \\\"__name__\\\",\\n               \\\"cluster\\\",\\n               \\\"job\\\",\\n               \\\"instance\\\",\\n               \\\"mode\\\",\\n               TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) total\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memFree\\\"\\n                    FROM \\\"druid\\\".\\\"clymene\\\"\\n                    WHERE \\\"__name__\\\" = 'node_memory_MemFree_bytes'\\n                    GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_free\\n             on total.__timestamp = mem_free.__timestamp\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memCached\\\"\\n                   FROM \\\"druid\\\".\\\"clymene\\\"\\n                   WHERE \\\"__name__\\\" = 'node_memory_Cached_bytes'\\n                   GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_cached\\n             on total.__timestamp = mem_cached.__timestamp\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memBuffer\\\"\\n                   FROM \\\"druid\\\".\\\"clymene\\\"\\n                   WHERE \\\"__name__\\\" = 'node_memory_Buffers_bytes'\\n                   GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_buffer\\n             on total.__timestamp = mem_buffer.__timestamp\\n        left join (SELECT TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S') AS \\\"__timestamp\\\",\\n                          avg(\\\"value\\\")                                     AS \\\"memSr\\\"\\n                   FROM \\\"druid\\\".\\\"clymene\\\"\\n                   WHERE \\\"__name__\\\" = 'node_memory_SReclaimable_bytes'\\n                   GROUP BY TIME_FLOOR(CAST(\\\"__time\\\" AS TIMESTAMP), 'PT30S')) mem_sr\\n             on total.__timestamp = mem_sr.__timestamp\\nwhere total.__timestamp >= MILLIS_TO_TIMESTAMP(${__from})\\n  AND total.__timestamp < MILLIS_TO_TIMESTAMP(${__to})\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{}}"
    }
   ]
  }
 ]
}