{
 "title": "Kubernetes Pods/Containers Resource Utilization Dashboard",
 "description": "Display usage of resources by pod or container in kubernetes cluster.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "Container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "POD/Container CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[5m])\r) by (pod, container)"
    },
    {
     "expr": "\r\n\rsum(\r\n      rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}[5m])\r\n    ) by (pod, container,)\r\n      /\r\n    sum(\r\n      container_spec_cpu_quota{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"} / container_spec_cpu_period{image!=\"\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}\r\n    ) by (pod, container)\r\n\r"
    }
   ]
  },
  {
   "title": "POD/Container RAM",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (pod, container, namespace)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\", namespace=\"$namespace\",container=~\"$container\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\", namespace=\"$namespace\",container=~\"$container\"}) by (container,pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}) by (container,pod)"
    }
   ]
  },
  {
   "title": "POD/Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{image!=\"\", namespace=\"$namespace\", pod=~\"$pod\", container=~\"$container\",container!=\"POD\"}[1m]))",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_cpu_cores{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\", container=~\"$container\", container!=\"POD\"}",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "POD/Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"$pod\",container!=\"POD\",container!=\"\",image!=\"\", namespace=\"$namespace\",container=~\"$container\"}",
     "legendFormat": "Current: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_requests_memory_bytes{pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}",
     "legendFormat": "Requested: {{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{pod=~\"$pod\", container!=\"POD\", container=~\"$container\"}",
     "legendFormat": "Limit: {{ pod }}"
    }
   ]
  },
  {
   "title": "POD/Container Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])  ",
     "legendFormat": "TX : {{ pod }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod }}"
    }
   ]
  }
 ]
}