version: '2'
services:
  clymene-agent:
    image: bourbonkk/clymene-agent:latest
    ports:
      - "15691:15691"
      - "15692:15692"
    environment:
      - STORAGE_TYPE=elasticsearch
    volumes:
      - ./config/clymene_scrape_config.yml:/etc/clymene/clymene.yml
    command:
      - --log-level=debug
      - --es.server-urls=http://localhost:9200

  clymene-ingester:
    image: bourbonkk/clymene-ingester:latest
    ports:
      - "15694:15694"
    environment:
#      - STORAGE_TYPE=elasticsearch,prometheus   # use composite writer
      - STORAGE_TYPE=elasticsearch
    command:
      - --log-level=debug
      - --kafka.consumer.brokers=[KAFKA-IP]:9092
      - --es.server-urls=http://[ELASTICSEARCH-IP]:9200
#      - --prometheus.remote.url=http://prometheus:9090/api/v1/write

  clymene-gateway:
    image: bourbonkk/clymene-gateway:latest
    ports:
      - "15610:15610"
      - "15690:15690"
    environment:
      - STORAGE_TYPE=elasticsearch
    command:
      - --log-level=debug
      - --es.server-urls=http://[ELASTICSEARCH-IP]:9200
