version: '2'
services:
  clymene-agent:
    image: bourbonkk/clymene-agent:main
    ports:
      - "15691:15691"
      - "15692:15692"
    environment:
      - TS_STORAGE_TYPE=kafka
    volumes:
      - "/"
