version: '2'
services:
  opentsdb:
    hostname: otsdb-host
    image: petergrace/opentsdb-docker:latest
    environment:
      - WAITSECS=30
    volumes:
      - ./config/opentsdb.conf:/etc/opentsdb/opentsdb.conf
    ports:
      - "4242:4242"
      - "9091:60030"