pipeline {
    environment {
        registry = "clymene/agent"
        registryCredential = 'dockerhub'
        branch = env.GIT_BRANCH
    }
    agent any
    stages {
        stage('docker build') {
            steps {
                sh 'docker build -t $registry:$branch'
            }
        }
        stage('docker deploy') {
            steps {
                withDockerRegistry([ credentialsId: registryCredential, url: "" ]) {
                    sh 'docker push $registry:$branch'
                }
            }
        }
        stage('Clean docker image') {
            steps{
                sh "docker rmi $registry"
            }
        }
    }
}