pipeline {
    environment {
        registry = "clymene/agent"
        registryCredential = 'dockerhub'
    }
    agent any
    stages {
        stage('docker build') {
            steps {
                bat 'docker build -t '+ registry+':'+env.GIT_BRANCH+' .'
            }
        }
        stage('docker deploy') {
            steps {
                withDockerRegistry([ credentialsId: registryCredential, url: "" ]) {
                    bat 'docker push '+ registry+':'+env.GIT_BRANCH
                }
            }
        }
        stage('Clean docker image') {
            steps{
                bat "docker rmi $registry"
            }
        }
    }
}