pipeline {
    environment {
        registry = "clymene/agent"
        registryCredential = 'dockerhub'
    }
    agent any
    stages {
        stage('docker build') {
            steps {
                sh 'docker build -t $registry:'+env.GIT_BRANCH
            }
        }
        stage('docker deploy') {
            steps {
                withDockerRegistry([ credentialsId: registryCredential, url: "" ]) {
                    sh 'docker push $registry:'+env.GIT_BRANCH
                }
            }
        }
        stage('Clean docker image') {
            steps{
                sh "docker rmi $registry"
            }
        }
    }
}