package mocks

import mock "github.com/stretchr/testify/mock"
import model "datagate/model"

// Unmarshaller is an autogenerated mock type for the Unmarshaller type
type Unmarshaller struct {
	mock.Mock
}

// Unmarshal provides a mock function with given fields: _a0
func (_m *Unmarshaller) Unmarshal(_a0 []byte) (*model.Span, error) {
	ret := _m.Called(_a0)

	var r0 *model.Span
	if rf, ok := ret.Get(0).(func([]byte) *model.Span); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Span)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
