name: Docker Image CI

on:
  push:
    branches:
    - main
    - "v*"
  pull_request:
    branches:
    - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Fetch git tags
        run: |
          git fetch --prune --unshallow --tags

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

#      - name: Setup BRANCH
#        shell: bash
#        run: |
#          case ${GITHUB_EVENT_NAME} in
#          pull_request)
#           BRANCH=${GITHUB_HEAD_REF}
#           ;;
#          push | release)
#           BRANCH=${GITHUB_REF##*/}
#           ;;
#          esac
#          echo "we are on branch=${BRANCH}"
#          echo "BRANCH=${BRANCH}" >> ${GITHUB_ENV}

      - name: Extract branch name
        id: extract_branch
        uses: keptn/gh-action-extract-branch-name@main

      - name: set env
        run: |
          echo "GIT_SHA=${{ steps.extract_branch.outputs.GIT_SHA }}" >> ${GITHUB_ENV}
          echo "BRANCH=${{ steps.extract_branch.outputs.BRANCH }}" >> ${GITHUB_ENV}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build clymene ingester
        run: bash scripts/build-clymene-ingester.sh


