name: Docker Image CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Fetch git tags
        run: |
          git fetch --prune --unshallow --tags

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Export BRANCH variable
        uses: ./.github/actions/setup-branch

      - name: Build clymene agent
        run: bash scripts/build-clymene-agent.sh

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
