name: Docker Image CI

on:
  push:
    branches:
    - master
    - "v*"
  pull_request:
    branches:
    - "**"

env:
  IMAGE_REGISTRY: quay.io
  REGISTRY_USER: ${{ secrets.QUAY_USERNAME }}
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Fetch git tags
        run: |
          git fetch --prune --unshallow --tags

      - uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH

      - name: Extract branch name
        id: extract_branch
        uses: keptn/gh-action-extract-branch-name@main

      - name: set env
        run: |
          echo "GIT_SHA=${{ steps.extract_branch.outputs.GIT_SHA }}" >> ${GITHUB_ENV}
          echo "BRANCH=${{ steps.extract_branch.outputs.BRANCH }}" >> ${GITHUB_ENV}
          echo "DATE=${{ steps.current-time.outputs.time }}" >> ${GITHUB_ENV}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Log in to Quay.io
        uses: redhat-actions/podman-login@v1
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: ${{ env.IMAGE_REGISTRY }}

      - name: Build clymene gateway
        run: bash scripts/build-clymene-gateway.sh


